/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          900: '#0c4a6e',
          950: '#082f49',
        },
        sw: {
          bg: 'var(--sw-bg)',
          surface: 'var(--sw-surface)',
          subtle: 'var(--sw-subtle)',
          hover: 'var(--sw-hover)',
          fg: 'var(--sw-fg)',
          'fg-2': 'var(--sw-fg-2)',
          'fg-muted': 'var(--sw-fg-muted)',
          'fg-faint': 'var(--sw-fg-faint)',
          brand: 'var(--sw-brand)',
          'brand-bg': 'var(--sw-brand-bg)',
          'brand-bd': 'var(--sw-brand-bd)',
          border: 'var(--sw-border)',
          'border-in': 'var(--sw-border-in)',
          'border-sub': 'var(--sw-border-sub)',
          'ok-bg': 'var(--sw-ok-bg)',
          'ok-fg': 'var(--sw-ok-fg)',
          'err-bg': 'var(--sw-err-bg)',
          'err-fg': 'var(--sw-err-fg)',
          'err-bd': 'var(--sw-err-bd)',
          'warn-bg': 'var(--sw-warn-bg)',
          'warn-fg': 'var(--sw-warn-fg)',
          'info-bg': 'var(--sw-info-bg)',
          'info-fg': 'var(--sw-info-fg)',
          'neut-bg': 'var(--sw-neut-bg)',
          'neut-fg': 'var(--sw-neut-fg)',
        },
      },
    },
  },
  plugins: [],
}
