"""initial schema

Revision ID: 285a94f840e1
Revises:
Create Date: 2026-02-23 09:09:41.011988

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "285a94f840e1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_accounts",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=True),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "storage_locations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type", sa.Enum("posix", "s3", "cifs", "nfs", name="storagetype"), nullable=False
        ),
        sa.Column("connection_config", sa.JSON(), nullable=True),
        sa.Column("base_path", sa.String(length=1024), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("role", sa.Enum("admin", "user", name="userrole"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "instruments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("pid", sa.String(length=255), nullable=True),
        sa.Column("cifs_host", sa.String(length=255), nullable=False),
        sa.Column("cifs_share", sa.String(length=255), nullable=False),
        sa.Column("cifs_base_path", sa.String(length=1024), nullable=True),
        sa.Column("service_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "transfer_adapter",
            sa.Enum("rclone", "globus", "rsync", name="transferadaptertype"),
            nullable=False,
        ),
        sa.Column("transfer_config", sa.JSON(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["service_accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "file_records",
        sa.Column("persistent_id", sa.String(length=255), nullable=False),
        sa.Column(
            "persistent_id_type",
            sa.Enum("ark", "doi", "handle", name="persistentidtype"),
            nullable=False,
        ),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source_path", sa.String(length=2048), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("source_mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("xxhash", sa.String(length=64), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("first_discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_file_records_instrument_source",
        "file_records",
        ["instrument_id", "source_path"],
        unique=True,
    )
    op.create_index(
        op.f("ix_file_records_persistent_id"), "file_records", ["persistent_id"], unique=True
    )
    op.create_table(
        "harvest_schedules",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("default_storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("prefect_deployment_id", sa.String(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["default_storage_location_id"],
            ["storage_locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hook_configs",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "trigger", sa.Enum("pre_transfer", "post_transfer", name="hooktrigger"), nullable=False
        ),
        sa.Column(
            "implementation",
            sa.Enum("builtin", "python_script", "http_webhook", name="hookimplementation"),
            nullable=False,
        ),
        sa.Column("builtin_name", sa.String(length=255), nullable=True),
        sa.Column("script_path", sa.String(length=1024), nullable=True),
        sa.Column("webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("instrument_id", sa.Uuid(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_instrument_access",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "instrument_id"),
    )
    op.create_table(
        "file_transfers",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("storage_location_id", sa.Uuid(), nullable=False),
        sa.Column("destination_path", sa.String(length=2048), nullable=True),
        sa.Column(
            "transfer_adapter",
            sa.Enum("rclone", "globus", "rsync", name="transferadaptertype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "in_progress", "completed", "failed", "skipped", name="transferstatus"
            ),
            nullable=False,
        ),
        sa.Column("bytes_transferred", sa.BigInteger(), nullable=True),
        sa.Column("source_checksum", sa.String(length=128), nullable=True),
        sa.Column("dest_checksum", sa.String(length=128), nullable=True),
        sa.Column("checksum_verified", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prefect_flow_run_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["file_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storage_location_id"],
            ["storage_locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_memberships",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    op.create_table(
        "project_memberships",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("member_type", sa.Enum("user", "group", name="membertype"), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "member_type", "member_id"),
    )
    op.create_table(
        "file_access_grants",
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column(
            "grantee_type", sa.Enum("user", "group", "project", name="granteetype"), nullable=False
        ),
        sa.Column("grantee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_access_grants")
    op.drop_table("project_memberships")
    op.drop_table("group_memberships")
    op.drop_table("file_transfers")
    op.drop_table("user_instrument_access")
    op.drop_table("hook_configs")
    op.drop_table("harvest_schedules")
    op.drop_index(op.f("ix_file_records_persistent_id"), table_name="file_records")
    op.drop_index("ix_file_records_instrument_source", table_name="file_records")
    op.drop_table("file_records")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("projects")
    op.drop_table("groups")
    op.drop_table("storage_locations")
    op.drop_table("service_accounts")
    # ### end Alembic commands ###
